/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int> mp;
        for(auto i:s)
        {
            mp[i]++;
        }
        for(auto i:t)
        {
            if(mp.find(i)!=mp.end())
            {
                mp[i]--;
                if(mp[i]==0)
                {
                    mp.erase(i);
                }
            }
            else{
                return i;
            }
        }
        return -1;
    }
};